import "react-toastify/dist/ReactToastify.css";

import "../(site)/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KODING AKADEMI DEMO",
  description: "Generated by NEXT APP",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="flex justify-center items-center min-h-screen bg-neutral-200 dark:bg-neutral-700">
          <div className="container h-full p-4">
            <div className=" flex h-full flex-wrap items-center justify-center text-neutral-800 dark:text-neutral-200">
              <div className="w-full">
                <div className=" rounded-lg bg-white shadow-lg dark:bg-neutral-800">
                  <div className="lg:flex lg:flex-wrap">
                    <div className="px-4 md:px-0 lg:w-6/12">
                      <div className="md:mx-6 md:p-12">
                        {/* --------------- LOGO --------------- */}
                        <div className="text-center mb-4">
                          <img
                            className="mx-auto w-24"
                            src="https://www.kodingakademi.id/wp-content/uploads/2022/09/56effd.gif"
                            alt="logo"
                          />
                          <h4 className=" mt-1 pb-1 text-xl font-semibold">
                            Koding Akademi
                          </h4>
                        </div>
                        {/* --------------- LOGO --------------- */}
                        {children}
                      </div>
                    </div>

                    <div className="flex items-center rounded-b-lg lg:w-6/12 lg:rounded-r-lg lg:rounded-bl-none bg-slate-600">
                      <div className="px-4 py-6 text-white md:mx-6 md:p-12">
                        <h4 className="mb-6 text-xl font-semibold">
                          Rental Car Company
                        </h4>
                        <p className="text-sm">
                          Lorem ipsum dolor sit amet, consectetur adipisicing
                          elit, sed do eiusmod tempor incididunt ut labore et
                          dolore magna aliqua. Ut enim ad minim veniam, quis
                          nostrud exercitation ullamco laboris nisi ut aliquip
                          ex ea commodo consequat.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <ToastContainer
          position="top-center"
          hideProgressBar={false}
          pauseOnFocusLoss={false}
        />
      </body>
    </html>
  );
}
